package com.hui10.app.model.user;

import java.util.Date;

public class WithdrawRecord {
	
	private String id;
	private String uid;
	private String tradeno;
	private String orderid;
	private String payeeno;
	private String payeename;
	private String payeebank;
	private Double cash;
	private Double fee;
	private String status;
	private String remark;
	private Date createtime;
	private Date updatetime;
	
	private String destinationcode;
    private String destinationname;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.uid
	 *
	 * @param uid
	 *            the value for hui_app_user_withdraw.uid
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.tradeno
	 *
	 * @return the value of hui_app_user_withdraw.tradeno
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public String getTradeno() {
		return tradeno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.tradeno
	 *
	 * @param tradeno
	 *            the value for hui_app_user_withdraw.tradeno
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setTradeno(String tradeno) {
		this.tradeno = tradeno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.payeeno
	 *
	 * @return the value of hui_app_user_withdraw.payeeno
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public String getPayeeno() {
		return payeeno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.payeeno
	 *
	 * @param payeeno
	 *            the value for hui_app_user_withdraw.payeeno
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setPayeeno(String payeeno) {
		this.payeeno = payeeno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.payeename
	 *
	 * @return the value of hui_app_user_withdraw.payeename
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public String getPayeename() {
		return payeename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.payeename
	 *
	 * @param payeename
	 *            the value for hui_app_user_withdraw.payeename
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setPayeename(String payeename) {
		this.payeename = payeename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.payeebank
	 *
	 * @return the value of hui_app_user_withdraw.payeebank
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public String getPayeebank() {
		return payeebank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.payeebank
	 *
	 * @param payeebank
	 *            the value for hui_app_user_withdraw.payeebank
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setPayeebank(String payeebank) {
		this.payeebank = payeebank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.cash
	 *
	 * @return the value of hui_app_user_withdraw.cash
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public Double getCash() {
		return cash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.cash
	 *
	 * @param cash
	 *            the value for hui_app_user_withdraw.cash
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setCash(Double cash) {
		this.cash = cash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.fee
	 *
	 * @return the value of hui_app_user_withdraw.fee
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public Double getFee() {
		return fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.fee
	 *
	 * @param fee
	 *            the value for hui_app_user_withdraw.fee
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setFee(Double fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.status
	 *
	 * @return the value of hui_app_user_withdraw.status
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.status
	 *
	 * @param status
	 *            the value for hui_app_user_withdraw.status
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.remark
	 *
	 * @return the value of hui_app_user_withdraw.remark
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.remark
	 *
	 * @param remark
	 *            the value for hui_app_user_withdraw.remark
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.createtime
	 *
	 * @return the value of hui_app_user_withdraw.createtime
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.createtime
	 *
	 * @param createtime
	 *            the value for hui_app_user_withdraw.createtime
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column hui_app_user_withdraw.updatetime
	 *
	 * @return the value of hui_app_user_withdraw.updatetime
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column hui_app_user_withdraw.updatetime
	 *
	 * @param updatetime
	 *            the value for hui_app_user_withdraw.updatetime
	 *
	 * @mbg.generated Thu Oct 19 10:24:12 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getDestinationcode() {
		return destinationcode;
	}

	public void setDestinationcode(String destinationcode) {
		this.destinationcode = destinationcode;
	}

	public String getDestinationname() {
		return destinationname;
	}

	public void setDestinationname(String destinationname) {
		this.destinationname = destinationname;
	}

	public String getOrderid() {
		return orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}
	
	
	
}